client:
  organization: dev
  logging:
    level: info
channels:
  _default:
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 2
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
    peers:
      test-peer:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    orderers:
      - test-orderer
organizations:
  dev:
    mspid: ORG1
    cryptoPath: do-not-use
    peers:
      - test-peer
    users:
      dhkim:
        cert:
          path: "/Users/dhkim/Projects/kiesnet-chaincode-dev-network/crypto-config/peerOrganizations/kiesnet.dev/users/dhkim/msp/signcerts/cert.pem"
        key:
          path: "/Users/dhkim/Projects/kiesnet-chaincode-dev-network/crypto-config/peerOrganizations/kiesnet.dev/users/dhkim/msp/keystore/ecd808d04162d2f53441067459e98c5377adaecb1c61a2e4f878d15c31858a00_sk"
orderers:
  test-orderer:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: localhost
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
peers:
  test-peer:
    url: localhost:7051
    grpcOptions:
      ssl-target-name-override: localhost
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true